install load bal

diff --git a/0x0F-load_balancer/1-install_load_balancer b/0x0F-load_balancer/1-install_load_balancer
--- a/0x0F-load_balancer/1-install_load_balancer
+++ b/0x0F-load_balancer/1-install_load_balancer
@@ -1,4 +1,21 @@
-#!/bin/bash
+#!/usr/bin/env bash
+# Install load balancer
+
+echo "Updating and doing some minor checks..."
+
+function install() {
+    if ! command -v "$1" &> /dev/null; then
+        echo "Installing: $1"
+        sudo apt-get update -y -qq && \
+            sudo apt-get install -y "$1" -qq || {
+                echo "Error: Failed to install $1"
+                exit 1
+            }
+        echo
+    else
+        echo "${1} is already installed."
+    fi
+}
 
 # Install HAProxy
 sudo apt-get update
@@ -8,9 +25,9 @@ sudo apt-get install -y haproxy
 cat <<EOF | sudo tee /etc/haproxy/haproxy.cfg >/dev/null
 defaults
     mode http
-    timeout connect 5000ms
-    timeout client 50000ms
-    timeout server 50000ms
+    timeout connect 5s
+    timeout client 10s
+    timeout server 15s
 
 frontend http_front
     bind *:80
